### ISSUE TITLE
Onboarding - CORS configuration can conflict with django-cors-headers app configuration if used

### ISSUE THREAD

**Issue by arnaudbesnier** [ForestAdmin/django-forestadmin#69]
## Expected behavior

Using the app `django-cors-headers`, the onboarding should be smooth.

## Actual behavior

Onboarding on a Django backend using the app `django-cors-headers` seems to conflict with the agent CORS configuration and does not let the Forest Admin client request the backend.
By manually adding `app.forestadmin.com`, as an authorized domain to the `django-cors-headers` configuration, we manage to bypass the issue.

## Context

* Package Version: 1.0.5
* Django Version: unknown

**Comment by vamonte** [comment]
The cors policies settings are been updated in this PR https://github.com/ForestAdmin/django-forestadmin/pull/77 .
It fixes the CORS issues.
