### ISSUE TITLE
Onboarding - No schema synchronisation on server start, developer stuck in the last onboarding page "waiting for your backend to run..."

### ISSUE THREAD

**Issue by arnaudbesnier** [ForestAdmin/django-forestadmin#70]
## Expected behavior

The onboarding should be smooth with a schema synchronisation success that let the developer enter its newly generated admin panel.

## Actual behavior

The developer is stuck, "waiting for the backend to run...", because the `.forestadmin-schema.json` is not sent to Forest Admin on backend application start. Is the  ̀forestadmin-schema.json` generated? 🤷‍♂️ 

## Failure Logs

- [x] Did the server started properly and is accessible?
- [ ] Is the `.forestadmin-schema.json` generated?
- [ ] Can we see the logs generated on start?

## Context

* Package Version: v1.0.5
* Django Version: ?

**Comment by SeyZ** [comment]
Hey @n6g7 any chance to try to comment one by one your Django Apps easily to see if the file `.forestadmin-schema.json` is generated? It would be super helpful! Let me know if I can help on my side.
