### ISSUE TITLE
ModuleNotFoundError: No module named 'pytz'

### ISSUE THREAD

**Issue by vamonte** [ForestAdmin/django-forestadmin#74]
## Expected behavior

Start a new Django 4 project with the forestadmin agent.

## Actual behavior

ModuleNotFoundError: No module named 'pytz'

## Failure Logs

```bash
  from django_forest.utils.scope import ScopeManager
  File "/Users/xxxx/fadmin/pvenv/forestDemo/lib/python3.9/site-packages/django_forest/utils/scope.py", line 6, in <module>
  import pytz
  ModuleNotFoundError: No module named 'pytz'
```

## Context

The new django version use the `zoneinfo` package instead of the `pytz` package. (https://docs.djangoproject.com/fr/4.0/releases/4.0/)

Zoneinfo is available in python >= 3.9
One backport is mandatory to use zoneinfo with python < 3.9. Its backport is only available for python >= 3.6

* Django Version: 4.0.1

**Comment by GuillaumeCisco** [comment]
Hello @vamonte,

This python SDK is currently only available up to Django 3.x.
Stay tuned  for Django 4.x support ;)
